services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skyhawk
      POSTGRES_PASSWORD: skyhawk
      POSTGRES_DB: NBA
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--appendfsync", "everysec",
      "--save", "900", "1",
      "--save", "300", "10",
      "--save", "60", "10000",
      "--loglevel", "warning"
    ]

  events:
    build:
      context: .
      dockerfile: events/Dockerfile
    command: ["/events"]
    container_name: events
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - postgres
    environment:
      POSTGRES_DSN: postgres://skyhawk:skyhawk@postgres:5432/NBA?sslmode=disable
      REDIS_ADDR: redis:6379

  statistics:
    build:
      context: .
      dockerfile: statistics/Dockerfile
    command: ["/statistics"]
    container_name: statistics
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379

volumes:
  postgres_data:
  redis_data:
